control_usuarios/urls.py
from django.urls import path

#from . import views
from .views import servicio
from .views import views
from .views import contrato

urlpatterns = [
    path('', views.index, name='index'),
    path('login/',views.mlogin,name="login"),
    path('login/try',views.try_login,name="try_login"),
    path('logout/',views.mlogout,name="logout"),
    path('bill/pay', views.capture_bill_payment, name='pay_bill'),
    path('send_email/', views.send_email_to_client, name='send_email'),
    path('testr/',views.some_view,name="test_pdf"),
    path('contract/add',views.contract_add,name="contract_add"),
    path('contract/save',views.contract_save,name="contract_save"),
    path('services/',servicio.services,name="services"),
    path('services/save',servicio.service_save,name="service_save"),
    path('services/delete',servicio.service_delete,name="service_delete"),
    path('services/<int:service_id>/',servicio.service_edit, name='service_edit'),
    path('services/<int:service_id>/update',servicio.service_update, name='service_update'),
    path('clients/',views.clients,name="clients"),
    path('clients/<int:client_id>/',views.client,name="client"),
    path('clients/<int:client_id>/contracts/<int:contract_id>/',contrato.client_with_contract_details,name="client_with_contract"),
    path('clients/<int:client_id>/editar',views.client_edit,name="client_edit"),
    path('clients/anadir',views.client_add,name="client_add"),
    path('clients/<int:client_id>/add_contract',views.client_add_contract,name="client_add_contract"),
    path('clients/save',views.client_save,name="client_save"),
    path('clients/update/<int:client_id>',views.client_update,name="client_update"),
    path('clients/delete',views.client_delete,name="client_delete"),
]

raulwalle/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('control_usuarios/', include('control_usuarios.urls')),
    path('admin/', admin.site.urls),
]

control_usuarios/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Cliente(models.Model):
    clave = models.CharField(max_length=200)
    nombre = models.CharField(max_length=200)
    fecha_nacimiento = models.CharField(max_length=10,default="14/10/2018")
    sexo = models.CharField(max_length=1,default="O")
    email = models.CharField(max_length=50,default="")
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

class Servicio(models.Model):
    nombre = models.CharField(max_length=200)
    clave = models.CharField(max_length=5)
    costo = models.DecimalField(default=0.00, max_digits=6, decimal_places=2)
    tiene_usuarios = models.BooleanField(default=False)
    clientes = models.ManyToManyField(Cliente, through='Contratos')

    def __str__(self):
        return self.nombre

    # def get_absolute_url(self):
    #     return reverse('service-detail',kwargs={'pk':self.pk})
    
    def get_absolute_url(self):
        return reverse('services')

class Contratos(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    fecha_contrato = models.DateField()
    direccion_servicio = models.CharField(max_length=200,default="")

    def __str__(self):
        return ""+ str(self.id) +"_"+ self.cliente.nombre +"__"+self.servicio.nombre+""
    #agregar al modelo fecha vencimiento

class Factura(models.Model):
    contrato = models.ForeignKey(Contratos, on_delete=models.CASCADE)
    fecha_factura = models.DateField()
    fecha_vencimiento = models.DateField()
    pagado = models.BooleanField(default=False)

    def __str__(self):
        return self.contrato.cliente.clave+ "_" + self.contrato.servicio.nombre+"--" + self.fecha_factura.strftime("%Y-%m-%d")

class Usuario(models.Model):
    contrato = models.ForeignKey(Contratos, on_delete=models.CASCADE,default=1)
    usuario = models.CharField(max_length=200)
    clave = models.CharField(max_length=200)

class Tipo_Usuario(models.Model):
    descripcion = models.CharField(max_length=200)
    

control_usuarios/views/contrato.py
from django.views.generic.edit import UpdateView
from django import forms
from control_usuarios.models import Contratos

from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse, HttpResponseRedirect, Http404

from django.contrib.auth.decorators import login_required

class ContratoUpdate(UpdateView):
    model = Contratos
    fields = ['clave','nombre','costo','tiene_usuarios']

@login_required(login_url='login/')
def client_with_contract_details(request,client_id,contract_id):
    contrato = get_object_or_404(Contratos,pk=contract_id)
    
    return render(request,'control_usuarios/contract_details.html',{
        'contrato' : contrato
        })

    

control_usuarios/views/servicio.py
from django.views.generic.edit import UpdateView
from django import forms
from control_usuarios.models import Servicio

from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse, HttpResponseRedirect, Http404

from django.urls import reverse
from django.contrib import messages

from django.contrib.auth.decorators import login_required

import re

@login_required(login_url='login/')
def services(request):
    servicios_lista = Servicio.objects.all().order_by('clave')
    context = {'servicios': servicios_lista}
    return render(request,'control_usuarios/services.html', context)

@login_required(login_url='login/')
def service_save(request):
    try:
        servicio_clave = request.POST["edit_text_clave_servicio"]
        servicio_descripcion = request.POST["edit_text_descripcion_servicio"]
        servicio_costo = request.POST["edit_text_costo_servicio"]
    except(KeyError):
        return render(request,'control_usuarios/services.html',{ 
            'message': "Falta Información"
            })
    else:

        servicio_tiene_usuarios = False
        if request.POST.get("edit_text_numero_usuarios_servicio", "0") == "1":
            servicio_tiene_usuarios = True


        nuevo_servicio = Servicio(clave=servicio_clave,nombre=servicio_descripcion,costo=servicio_costo,tiene_usuarios=servicio_tiene_usuarios)
        nuevo_servicio.save()

        return HttpResponseRedirect(reverse('services'))

@login_required(login_url='login/')
def service_delete(request):
    try:
        servicio_id = request.POST["edit_text_id_servicio"]
        servicio = get_object_or_404(Servicio,pk=servicio_id)
    except(KeyError):
        return render(request,'control_usuarios/services.html',{ 
            'message': "Falta Información"
            })
    except(Servicio.DoesNotExist):
        raise Http404("Servicio no existe")
    else:
        servicio.delete()
    return HttpResponseRedirect(reverse('services'))

@login_required(login_url='login/')
def service_edit(request,service_id):
    servicio = get_object_or_404(Servicio,pk=service_id)
    
    return render(request,'control_usuarios/service.html',{
        'servicio' : servicio
        })

@login_required(login_url='login/')
def service_update(request,service_id):
    servicio = get_object_or_404(Servicio,pk=service_id)

    try:
        servicio_clave = request.POST["edit_text_clave_servicio"]
        servicio_nombre = request.POST["edit_text_descripcion_servicio"]
        servicio_costo = request.POST["edit_text_costo_servicio"]
        # servicio_tiene_usuarios = request.POST["edit_text_numero_usuarios_servicio"]
    except(KeyError):
        messages.error(request,"faltan datos!")
        return HttpResponseRedirect(reverse('service_edit',kwargs={'service_id': service_id}))
    else:

        servicio_tiene_usuarios = request.POST.get("edit_text_numero_usuarios_servicio",False)

        servicio.clave = servicio_clave
        servicio.nombre = servicio_nombre
        servicio.costo = servicio_costo
        servicio.tiene_usuarios = servicio_tiene_usuarios

        servicio.save()

        return HttpResponseRedirect(reverse('services'))

control_usuarios/templates/control_usuarios/base.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

  <link rel="stylesheet" href="{% static 'control_usuarios/css/material.min.css' %}">
  <link rel="stylesheet" href="{% static 'control_usuarios/css/custom2.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'control_usuarios/css/custom.css' %}"> -->
  <!-- <link rel="stylesheet" href="{% static 'control_usuarios/css/stepper.css' %}"> -->
  <!-- <link rel="stylesheet" href="{% static 'control_usuarios/css/material-components-web.min.css' %}"> -->
  <!-- <link rel="stylesheet" href="{% static 'control_usuarios/css/mdc.textfield.min.css' %}"> -->
 
  <script src="{% static 'control_usuarios/js/material.min.js' %}"></script>
  <!-- <script src="{% static 'control_usuarios/js/stepper.js' %}"></script> -->
  <!-- <script src="{% static 'control_usuarios/js/material-components-web.min.js' %}"></script> -->
  <!-- <script src="{% static 'control_usuarios/js/mdc.autoInit.min.js' %}"></script> -->
  <!-- <script src="{% static 'control_usuarios/js/mdc.textfield.min.js' %}"></script> -->
  
  
  <script src="{% static 'control_usuarios/js/vue.min.js' %}"></script>
  <script src="{% static 'control_usuarios/js/vue-mdl.js' %}"></script>
  <script src="{% static 'control_usuarios/js/vue-the-mask.js' %}"></script>
  <script src="{% static 'control_usuarios/js/v-money.js' %}"></script>
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
{% block custom_body %}<body>{% endblock custom_body %}
  <!-- Always shows a header, even in smaller screens. -->
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header" id="app">
    <header class="mdl-layout__header custom-color--black-1">
      <div class="mdl-layout__header-row">

        {% block toolbar %}
        <!-- Title -->
        <span class="mdl-layout-title">Control Usuarios</span>
        <!-- Add spacer, to align navigation to the right -->
        <div class="mdl-layout-spacer"></div>
        <!-- Navigation. We hide it in small screens. -->
        <nav class="mdl-navigation mdl-layout--large-screen-only">
          <a class="mdl-navigation__link" href="">Link</a>
          <a class="mdl-navigation__link" href="">Link</a>
          <a class="mdl-navigation__link" href="">Link</a>
          <a class="mdl-navigation__link" href="">Link</a>
        </nav>
        {% endblock toolbar %}
      
      </div>
    </header>
    
    {% block sidebar %}
      {% include "control_usuarios/includes/drawer.html" %}
    {% endblock sidebar %}
    
    <main class="mdl-layout__content">
      {% block content %}
      {% endblock content %}
    </main>

    {% block drawer_right %}
    {% endblock drawer_right %}

    {% block dialog %}
    {% endblock dialog %}
  </div>

  {% block scripts %}
  {% endblock scripts %}

  

</body>
</html>

control_usuarios/templates/control_usuarios/clients.html
{% extends "control_usuarios/base.html" %}
{% load static %}

{% block custom_body %}<body class="mdl-color--white">{% endblock custom_body %}

{% block sidebar %}
  {% include "control_usuarios/includes/drawer.html" with active_menu="clientes" %}
{% endblock sidebar %}

{% block toolbar %}
<!-- Title -->
<span class="mdl-layout-title">Clientes</span>
<!-- Add spacer, to align navigation to the right -->
<div class="mdl-layout-spacer"></div>
<!-- Navigation. We hide it in small screens. -->
<a class="mdl-button mdl-js-button mdl-button--icon" href="{% url 'client_add' %}" style="margin-left: 16px;" >
  <i class="material-icons">person_add</i>
</a>
<form class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
  mdl-textfield--floating-label mdl-textfield--align-right">
  <label class="mdl-button mdl-js-button mdl-button--icon"
          for="fixed-header-drawer-exp">
    <i class="material-icons">search</i>
  </label>
  <div class="mdl-textfield__expandable-holder">
    <input class="mdl-textfield__input" type="search" name="search"
            id="fixed-header-drawer-exp">
  </div>
</form>
{% endblock toolbar %}
{% block content %}
<div class="page-content" style="padding-bottom: 72px;">
  <div class="mdl-grid">
    {% if clientes %}
    <div class="mdl-cell mdl-cell--7-col mdl-cell--12-col-phone mdl-list mdl-list--carbon">
      {% for cliente in clientes %}
      <div class="mdl-list__item mdl-list__item--with-divisor mdl-list__item--two-line selectable-list-item" v-on:click="showClientDetails({{cliente.id}})">
        <span class="mdl-list__item-primary-content mdl-js-ripple-effect">
          <span class="mdl-ripple"></span>
          <img src="{% static 'control_usuarios/img/user_placeholder2.png' %}"  class="mdl-list__item-avatar" alt="">
          <span>{{ cliente.nombre | title }}</span>
          <span class="mdl-list__item-sub-title">{{ cliente.clave }}</span>
        </span>
        <span class="mdl-list__item-secondary-content">
          <button class="mdl-list__item-secondary-action mdl-button mdl-js-button mdl-button--icon mdl-button--colored" onclick="event.stopPropagation();" @click="showDrawerRight('{{ cliente.email }}')">
              <i class="material-icons">mail_outline</i>
          </button>
        </span>
        <span class="mdl-list__item-secondary-content">
          <a class="mdl-list__item-secondary-action mdl-button mdl-js-button mdl-button--icon mdl-button--colored" onclick="event.stopPropagation();" href="tel:{{ cliente.telefono }}">
              <i class="material-icons">phone</i>
          </a>
        </span>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div class="mdl-cell mdl-cell--7-col">
        <p>No se encontraron resultados.</p>
    </div>
    {% endif %}
  
    <div class="mdl-cell mdl-cell--6-col">
      <div class="mdl-paging">
        {% if clientes.has_previous %}
          <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-paging__next mdl-button--colored" href="?page=1">
            <i class="material-icons">first_page</i>
          </a>
          <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-paging__next mdl-button--colored" href="?page={{ clientes.previous_page_number }}">
            <i class="material-icons">chevron_left</i>
          </a>
        {% endif %}
        <span class="mdl-paging__count">Page {{ clientes.number }} of {{ clientes.paginator.num_pages }}.</span>
        {% if clientes.has_next %}
          <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-paging__next mdl-button--colored" href="?page={{ clientes.next_page_number }}">
            <i class="material-icons">chevron_right</i>
          </a>
          <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-paging__next mdl-button--colored" href="?page={{ clientes.paginator.num_pages }}">
            <i class="material-icons">last_page</i>
          </a>
        {% endif %}
      </div>
    </div>

    {%if messages %}
      <mdl-snackbar display-on="opMsg"></mdl-snackbar>
    {% endif %}
  
  </div>

  <!-- Colored FAB button -->
  <a class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored mdl-cell--hide-desktop"
    style="position: fixed; right: 16px; bottom: 16px;"
    href="{% url 'client_add' %}"
    >
    <i class="material-icons">person_add</i>
  </a>      
</div>




{% endblock content %}

{% block dialog %}
<mdl-dialog ref="confirmDialog" id="confirmDialog" full-width>
    <h6>Eliminar este cliente?</h6>
    <template slot="actions">
        <form class="mdl-cell mdl-cell--12-col form-inline">
            {% csrf_token %}
            <input type="hidden" name="edit_text_id_cliente" v-model="customerToDelete">
            <button type="button" class="mdl-button mdl-js-button" v-on:click="closeDialogDelete">
                Cancelar
            </button>
            <button class="mdl-button mdl-js-button mdl-button--accent" type="submit" formaction="{% url 'client_delete' %}" formmethod="POST">
                Eliminar
            </button>
        </form>
    </template>
</mdl-dialog>
{% endblock dialog %}

{% block drawer_right %}
<div class="mdl-layout__drawer-right mdl-color--white" :class="{active: showRightDrawer}">
  <span class="mdl-layout-title mdl-color--carbon-500" style="color: white; font-size: 1rem; letter-spacing: .15rem; display: flex;">
    Mensaje Nuevo
    <div class="mdl-layout-spacer"></div>
    <button class="mdl-button mdl-js-button mdl-button--icon" style="align-self: center; margin-right: 16px;" @click="closeDrawerRight()" >
      <i class="material-icons">close</i>
    </button>
  </span>
  <form action="{% url 'send_email' %}" style="padding: 16px;" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label has-placeholder" style="width: 100%">
      <input class="mdl-textfield__input" type="text" id="edit_text_email_to" name="edit_text_email_to" readonly v-model="emailTo">
      <label class="mdl-textfield__label" for="edit_text_email_to">Para</label>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label has-placeholder" style="width: 100%">
      <input class="mdl-textfield__input" type="text" id="edit_text_asunto" name="edit_text_asunto">
      <label class="mdl-textfield__label" for="edit_text_asunto">Asunto</label>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label has-placeholder" style="width: 100%">
      <textarea class="mdl-textfield__input" type="text" rows="5" id="edit_text_body" name="edit_text_body" placeholder=""></textarea>
      <label class="mdl-textfield__label" for="edit_text_body">Cuerpo</label>
    </div>
    
    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
      <i class="material-icons">send</i> Enviar
    </button>
    <input type="file" id="edit_text_email_files" name="edit_text_email_files" style="display: none" multiple>
    <label for="edit_text_email_files" class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored">
      <i class="material-icons">attach_file</i>
    </label>
  </form>

</div>
{% endblock drawer_right %}

{% block scripts %}
<script>
  Vue.use(VueMdl.default);

  var userServicesApp = new Vue({
      delimiters: ['${','}$'],
      el: "#app",
      data: {
          customerToDelete: 0,
          showRightDrawer: false,
          emailTo: ""
      },
      mounted: function(){
          //this.$refs.confirm.open()

          {% if messages %}
            {% for message in messages %}
              this.$emit('opMsg', { message: '{{ message }}' })
            {% endfor %}
          {% endif %}

      },
      methods:{
          showDrawerRight:function(email){
            this.showRightDrawer = true;
            this.emailTo = email;
          },
          closeDrawerRight:function(){
            this.showRightDrawer = false;
          },
          showDialogDelete: function(idCliente){
              this.customerToDelete = idCliente
              this.$refs.confirmDialog.open()
          },
          closeDialogDelete: function(){
              this.$refs.confirmDialog.close()
          },
          showClientDetails: function(idCliente){
            location.href="{% url 'client' 0 %}".replace(/0/, idCliente.toString());

          }
      }
  })
</script>
{% endblock scripts %}

control_usuarios/templates/control_usuarios/contract_details.html
{% extends "control_usuarios/base.html" %}
{% load static %}

{% block custom_body %}<body class="mdl-color--aux-3">{% endblock custom_body %}

{% block toolbar %}
<!-- Title -->
<a  href="{% url 'client' contrato.cliente.id %}" class="mdl-button mdl-js-button mdl-button--icon">
    <i class="material-icons mdl-color-text--white">arrow_back</i>
</a>
<span class="mdl-layout-title" style="margin-left: 8px;">Orden #{{ contrato.id }} </span>
{% endblock toolbar %}

{% block content %}
<div class="page-content">
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--6-col">
            <div class="mdl-card mdl-card--carbon">
                <div class="mdl-card__title" style="font-size:1.125rem; margin-top:24px; margin-bottom:16px;">
                    Detalles de la Orden
                </div>
                <div class="mdl-card__supporting-text">
                    <p>Fecha Orden: <span class="mdl-color-text--carbon-500">{{ contrato.fecha_contrato | date:"Y-m-d"  }}</span></p>
                    <p>Dirección Instalación:</p>
                    <p><span class="mdl-color-text--carbon-500">{{ contrato.direccion_servicio }}</span></p>
                </div>

                {% if  contrato.usuario_set.all %}
                    <div class="mdl-card__title" style="font-size:1.125rem; margin-top:24px; margin-bottom:16px;">
                        Claves de Acceso
                    </div>
                    <div class="mdl-card__supporting-text">
                    {% for usuario in contrato.usuario_set.all %}
                        <p>Usuario: <span class="mdl-color-text--carbon-500">{{ usuario.usuario }}</span> </p>
                        <p>Contraseña: <span class="mdl-color-text--carbon-500">{{ usuario.clave}} </span></p>
                    {% endfor %}
                    </div>
                {% endif %}
            </div>
            
        </div>
        

    
    </div>
</div>
{% endblock content %}

control_usuarios/templates/control_usuarios/login.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

  <link rel="stylesheet" href="{% static 'control_usuarios/css/material.min.css' %}">
  <link rel="stylesheet" href="{% static 'control_usuarios/css/custom2.css' %}">
  <script src="{% static 'control_usuarios/js/material.min.js' %}"></script>
  
  
  <script src="{% static 'control_usuarios/js/vue.min.js' %}"></script>
  <script src="{% static 'control_usuarios/js/vue-mdl.js' %}"></script>
  <script src="{% static 'control_usuarios/js/vue-the-mask.js' %}"></script>
  <script src="{% static 'control_usuarios/js/v-money.js' %}"></script>
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body class="mdl-color--aux-3">
  <!-- Always shows a header, even in smaller screens. -->
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header" id="app">
    <header class="mdl-layout__header custom-color--black-1">
      <div class="mdl-layout__header-row">
        <span class="mdl-layout-title">Control Usuarios</span>
      </div>
    </header>
    <main class="mdl-layout__content" style="display:flex; flex-flow:column; justify-content:center; align-items:center;">
        <form class="mdl-card mdl-shadow--6dp" method="POST" action="{% url 'try_login' %}">{% csrf_token %}
            <div class="mdl-card__title">
                Login
            </div>
            <div class="mdl-card__supporting-text">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="text" id="edit_text_usuario" name="edit_text_usuario">
                    <label class="mdl-textfield__label" for="edit_text_usuario">Usuario</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="password" id="edit_text_contrasena" name="edit_text_contrasena">
                    <label class="mdl-textfield__label" for="edit_text_contrasena">Contraseña</label>
                </div>
            </div>
            <div class="mdl-card__actions" style="display:flex;">
                <div class="mdl-layout-spacer"></div>
                <button class="mdl-button mdl-js-button mdl-button--accent">
                    Iniciar Sesión
                </button>
            </div>
        </form>

        {% if messages %}
            {% for message in messages %}
                <div class="mdl-card mdl-color--red" style="margin-top:8px; min-height:72px;">
                    <div class="mdl-card__supporting-text mdl-color-text--white">
                        {{ message }}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </main>
  </div>



  

</body>
</html>

control_usuarios/templates/control_usuarios/service.html
{% extends "control_usuarios/base.html" %}
{% load static %}

{% block toolbar %}
<!-- Title -->
<span class="mdl-layout-title">Servicio {{ servicio.clave }}</span>
{% endblock toolbar %}

{% block content %}
<div class="page-content">
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--6-col">
            <form action="{% url 'service_update' servicio.id %}" method="post">{% csrf_token %}
                <div style="display:flex;flex-flow:column; align-items:center; width:332px;">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <input class="mdl-textfield__input" type="text" required id="edit_text_clave_servicio" name="edit_text_clave_servicio" value="{{ servicio.clave }}">
                        <label class="mdl-textfield__label" for="edit_text_clave_servicio">Clave</label>
                    </div>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <input class="mdl-textfield__input" type="text" required id="edit_text_descripcion_servicio" name="edit_text_descripcion_servicio" value="{{ servicio.nombre }}">
                        <label class="mdl-textfield__label" for="edit_text_descripcion_servicio">Descripción</label>
                    </div>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <label class="mdl-textfield__label" for="edit_text_costo_servicio">Costo</label>
                        <money class="mdl-textfield__input" v-model="serviceCosto" v-bind="money" required id="edit_text_costo_servicio"></money>
                    </div>

                    <input type="hidden" v-model="serviceCosto" name="edit_text_costo_servicio">

                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="edit_text_numero_usuarios_servicio" style="width:300px">
                        <input type="checkbox" class="mdl-checkbox__input" id="edit_text_numero_usuarios_servicio" name="edit_text_numero_usuarios_servicio" value="1" {% if servicio.tiene_usuarios %} checked="checked" {% endif %}>
                        <span class="mdl-checkbox__label">Tiene Usuarios</span>
                    </label>
    
                    <button type="submit" class="mdl-button mdl-js-button mdl-button--primary" style="align-self:flex-end; margin-right:16px;">
                        Guardar Cambios
                    </button>

                </div>
                
            </form>
        </div>

        {%if messages %}
        <mdl-snackbar display-on="opMsg"></mdl-snackbar>
        {% endif %}
    </div>
</div>
{% endblock content %}

{% block scripts %}
<!-- CODE -->
<script>
    Vue.use(VueMdl.default);

    var userServicesApp = new Vue({
        delimiters: ['${','}$'],
        el: "#app",
        data: {
            serviceToDelete: 0,
            serviceCosto: parseFloat("{{ servicio.costo }}"),
            money: {
                decimal: '.',
                thousands: ',',
                prefix: '$ ',
                suffix: '',
                precision: 2,
                masked: false
              }
        },
        mounted: function(){
            componentHandler.upgradeAllRegistered();

            {% if messages %}
                {% for message in messages %}
                    this.$emit('opMsg', { message: '{{ message }}' })
                {% endfor %}
            {% endif %}
        },
        methods:{
        }
    })
</script>
{% endblock scripts %}